package cc.yggdrasil.studyqrcode;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import org.springframework.stereotype.Component;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;

@Component
public class QrCodeForm
{
    private JButton btnClear;
    private JButton btnGenerate;
    private JPanel pnlQrCode;
    private JPanel pnlControls;
    private JPanel pnlPadding;
    private JPanel mainPanel;
    private JLabel lblQrCode;

    public QrCodeForm()
    {
        btnClear.addActionListener(e ->
        {
            System.out.println("Clear button clicked");

            disposeCurrentQrCode();

            lblQrCode.setIcon(null);
            lblQrCode.repaint();
        });

        btnGenerate.addActionListener(e ->
        {
            System.out.println("Generate button clicked");
            final String data = "timestamp: " + System.currentTimeMillis();
            final BufferedImage qrCode = createQR(data, "UTF-8", 300, 300);

            final ImageIcon icon = new ImageIcon(qrCode);
            lblQrCode.setIcon(icon);
            lblQrCode.repaint();
        });
    }

    /**
     * Dispose the current QR code image.
     */
    private void disposeCurrentQrCode()
    {
        if (lblQrCode.getIcon() instanceof ImageIcon oldIcon)
        {
            oldIcon.getImage()
                   .flush();
        }
    }

    /**
     * Create a QR code image.
     *
     * @param data the data to be encoded
     * @param charset the character set
     * @param height the image height
     * @param width the image width
     * @return the generated QR code image
     */
    private BufferedImage createQR(final String data, final String charset, int height, int width)
    {
        try
        {
            final BitMatrix matrix = new MultiFormatWriter().encode(
                    new String(data.getBytes(charset), charset),
                    BarcodeFormat.QR_CODE, width, height);

            return MatrixToImageWriter.toBufferedImage(matrix);
        }
        catch (final WriterException | IOException caught)
        {
            System.err.println("Failed to generate QR code: " + caught.getMessage());
        }

        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        pnlQrCode = new JPanel();
        pnlQrCode.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 8.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlQrCode, gbc);
        lblQrCode = new JLabel();
        lblQrCode.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        pnlQrCode.add(lblQrCode, gbc);
        pnlControls = new JPanel();
        pnlControls.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 2.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(pnlControls, gbc);
        btnClear = new JButton();
        btnClear.setText("Clear");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        pnlControls.add(btnClear, gbc);
        btnGenerate = new JButton();
        btnGenerate.setText("Generate");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        pnlControls.add(btnGenerate, gbc);
        pnlPadding = new JPanel();
        pnlPadding.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlPadding, gbc);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }

}
