package cc.yggdrasil.studyqrcode;

import org.springframework.stereotype.Component;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.image.BufferedImage;

@Component
public class QrCodeForm
{
    private JButton btnClear;
    private JButton btnGenerate;
    private JPanel pnlQrCode;
    private JPanel pnlControls;
    private JPanel pnlPadding;
    private JPanel mainPanel;
    private JLabel lblQrCode;
    private JPanel pnlInputData;
    private JTextArea txtAreaInputData;

    public QrCodeForm()
    {
        btnClear.addActionListener(e ->
        {
            disposeCurrentQrCode();

            lblQrCode.setIcon(null);
            lblQrCode.repaint();
        });

        btnGenerate.addActionListener(e ->
        {
            final QrCodeGenerator qrCodeGenerator = new QrCodeGenerator();
            final String data = qrCodeGenerator.makeQrCodeData(txtAreaInputData.getText());
            final BufferedImage qrCode = qrCodeGenerator.createQR(data, "UTF-8", 250, 250);
            final ImageIcon icon = new ImageIcon(qrCode);

            lblQrCode.setIcon(icon);
            lblQrCode.repaint();
        });
    }

    /**
     * Dispose of the current QR code image.
     */
    private void disposeCurrentQrCode()
    {
        if (lblQrCode.getIcon() instanceof ImageIcon oldIcon)
        {
            oldIcon.getImage()
                   .flush();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        pnlQrCode = new JPanel();
        pnlQrCode.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 7.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlQrCode, gbc);
        lblQrCode = new JLabel();
        lblQrCode.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        pnlQrCode.add(lblQrCode, gbc);
        pnlControls = new JPanel();
        pnlControls.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlControls, gbc);
        btnClear = new JButton();
        btnClear.setText("Clear");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        pnlControls.add(btnClear, gbc);
        btnGenerate = new JButton();
        btnGenerate.setText("Generate");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        pnlControls.add(btnGenerate, gbc);
        pnlPadding = new JPanel();
        pnlPadding.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlPadding, gbc);
        pnlInputData = new JPanel();
        pnlInputData.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 2.5;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pnlInputData, gbc);
        txtAreaInputData = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 50, 0, 50);
        pnlInputData.add(txtAreaInputData, gbc);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }

}
